name: Javascript testing
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
    - name: check out    
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}       
      uses: actions/setup-node@v2      
      with:
        node-version: ${{ matrix.node-version }}

    - name: run javascript test
      run: |
        npm install
        npm test